# Optional C++20 named module support for psi::pimpl (opt-in, off by default).
#
# Adds a target, `psi_pimpl_module` (alias `psi::pimpl_module`), exporting psi::pimpl's public
# headers as `import psi.pimpl;` instead of textual #include. Purely additive: psi_pimpl (the
# existing header-only INTERFACE target) is untouched, so any consumer vendoring these headers
# directly is unaffected regardless of whether this option exists.
#
# Shape: matches psiha/vm's own module.cmake (feat/module-support there) - the global module
# fragment carries the STL headers these headers use textually, since modules never export
# macros; the purview (`export extern "C++"`) carries every real header via file(GLOB_RECURSE),
# so a header added later is picked up automatically. psi::pimpl has no macro-only headers, no
# platform-specific files and no external (Boost) dependency, so there is nothing to exclude from
# the purview and nothing to link.
#
# Toolchain: clang-cl and the GNU-driver clang only; MSVC/GCC get a warning, not a hard error.

option( PSI_PIMPL_MODULE "Build psi.pimpl as a C++20 named module (opt-in; requires clang-cl or clang)" OFF )

if ( PSI_PIMPL_MODULE )
    if ( NOT ( CMAKE_CXX_COMPILER_ID MATCHES Clang ) )
        message( WARNING "PSI_PIMPL_MODULE requires clang-cl or clang; ignored on ${CMAKE_CXX_COMPILER_ID}." )
    else()
        if ( CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC" )
            cmake_path( GET CMAKE_CXX_COMPILER PARENT_PATH _psi_pimpl_llvm_bin )
            find_program( PSI_PIMPL_CLANG_SCAN_DEPS clang-scan-deps HINTS "${_psi_pimpl_llvm_bin}" REQUIRED )
            string( CONCAT CMAKE_CXX_SCANDEP_SOURCE
                "\"${PSI_PIMPL_CLANG_SCAN_DEPS}\" -format=p1689 -- <CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS>"
                " /TP <SOURCE> /c /Fo<OBJECT> /clang:-MT /clang:<DYNDEP_FILE> /clang:-MD /clang:-MF /clang:<DEP_FILE>"
                " > <DYNDEP_FILE>.tmp && \"${CMAKE_COMMAND}\" -E rename <DYNDEP_FILE>.tmp <DYNDEP_FILE>" )
            set( CMAKE_CXX_MODULE_MAP_FORMAT clang )
            set( CMAKE_CXX_MODULE_MAP_FLAG "@<MODULE_MAP_FILE>" )
            set( CMAKE_CXX_COMPILE_BMI "<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> /clang:-o<OBJECT> /clang:--precompile /TP <SOURCE>" )
        endif()

        file( GLOB_RECURSE psi_pimpl_module_headers RELATIVE "${CMAKE_CURRENT_LIST_DIR}/include" "${CMAKE_CURRENT_LIST_DIR}/include/*.hpp" )
        # No platform-specific or macro-only headers exist under include/psi/pimpl - both headers
        # go into the purview unconditionally.

        set( _psi_pimpl_module_purview "${CMAKE_CURRENT_BINARY_DIR}/psi_pimpl_module_purview.hpp" )
        set( _psi_pimpl_module_content "// Generated by module.cmake - every psi::pimpl public header, cumulative.\n" )
        foreach( h ${psi_pimpl_module_headers} )
            string( APPEND _psi_pimpl_module_content "#include <${h}>\n" )
        endforeach()
        file( WRITE "${_psi_pimpl_module_purview}" "${_psi_pimpl_module_content}" )

        set( _psi_pimpl_module_unit "${CMAKE_CURRENT_BINARY_DIR}/psi_pimpl_module.cppm" )
        file( WRITE "${_psi_pimpl_module_unit}" "\
module;
#include <cstddef>
#include <cstdint>
#include <memory>
#include <new>
#include <type_traits>
#include <utility>
export module psi.pimpl;
export extern \"C++\"
{
#include \"${_psi_pimpl_module_purview}\"
}
" )

        add_library( psi_pimpl_module STATIC )
        add_library( psi::pimpl_module ALIAS psi_pimpl_module )
        target_compile_features( psi_pimpl_module PUBLIC cxx_std_23 )
        target_sources( psi_pimpl_module PUBLIC FILE_SET CXX_MODULES BASE_DIRS "${CMAKE_CURRENT_BINARY_DIR}" FILES "${_psi_pimpl_module_unit}" )
        target_include_directories( psi_pimpl_module PUBLIC "${CMAKE_CURRENT_LIST_DIR}/include" )
        target_compile_options( psi_pimpl_module PRIVATE
            $<$<CXX_COMPILER_FRONTEND_VARIANT:MSVC>:/clang:-std=gnu++2c /clang:-Wno-include-angled-in-module-purview /clang:-Wno-reserved-module-identifier>
            $<$<NOT:$<CXX_COMPILER_FRONTEND_VARIANT:MSVC>>:-Wno-include-angled-in-module-purview -Wno-reserved-module-identifier>
        )
    endif()
endif()
